### ISSUE TITLE
Quay is not able to clone this repo when building images

### ISSUE THREAD

**Issue by kubasikus** [release-engineering/repotracker#14]
See the repo [builds](https://quay.io/repository/factory2/repotracker?tab=builds )

I've found a similar issue https://github.com/stephenh/mirror/issues/33, which suggests that re-adding the trigger should fix the problem.

**Comment by mikebonnet** [comment]
Deleted and readded the triggers and builds are now working again: https://quay.io/repository/factory2/repotracker/build/8d7687f0-1605-4a31-ac13-e6d399c6f22b

**Comment by kubasikus** [comment]
Awesome, thanks!
